---
title: "Untitled"
output: 
  flexdashboard::flex_dashboard
runtime:
  shiny
---

```{r global, include=FALSE}
# libraries
library(flexdashboard)
library(tidyverse)
library(shiny)
library(shinyjs)
library(plotly)
library(writexl)

# database
allometr_db <- pool::dbPool(
  RPostgreSQL::PostgreSQL(),
  user = 'guest',
  password = 'guest',
  dbname = 'allometr_db'
)

# tables
allometries_table <- dplyr::tbl(allometr_db, 'ALLOMETRIES') %>% dplyr::collect()
variables_thesaurus <- dplyr::tbl(allometr_db, 'THESAURUS_VARIABLES') %>% dplyr::collect()
cubication_thesaurus <- dplyr::tbl(allometr_db, 'THESAURUS_CUBICATION') %>%
  dplyr::collect()
```

Sidebar {.sidebar}
=====================================

#### Especify the desired constraints for the allometries:

```{r}
## TODO better input logic for autodetect available values
## TODO order of inputs, first variables, then other stuff

# shinyjs
useShinyjs(rmd = TRUE)

# shiny inputs defined here
# choices
allometry_choices <- allometries_table %>%
  dplyr::pull(allometry_level) %>%
  unique() %>% sort()
spatial_choices <- allometries_table %>%
  dplyr::pull(spatial_level) %>%
  unique() %>% sort()
functgroup_choices <- allometries_table %>%
  dplyr::pull(functional_group_level) %>%
  unique() %>% sort()
depvar_choices <- variables_thesaurus %>%
  dplyr::filter(var_dependent) %>%
  dplyr::pull(var_id) %>%
  magrittr::set_names(
    variables_thesaurus %>%
      dplyr::filter(var_dependent) %>%
      dplyr::pull(translation_eng)
  )
indepvars_choices <- variables_thesaurus %>%
  dplyr::filter(var_independent) %>%
  dplyr::pull(var_id) %>%
  magrittr::set_names(
    variables_thesaurus %>%
      dplyr::filter(var_independent) %>%
      dplyr::pull(translation_eng)
  )
cubication_choices <- cubication_thesaurus %>%
  dplyr::pull(cubication_shape_id) %>%
  c('any', .) #%>%
  # magrittr::set_names(
  #   cubication_thesaurus %>%
  #     dplyr::pull(translation_eng) %>%
  #     c('Any', .)
  # )
specialparam_choices <- allometries_table %>%
  dplyr::pull(special_param) %>% unique() %>% sort()
# inputs
shiny::tagList(
  # allometry
  shiny::selectInput(
    'allolvl', 'Allometry level',
    choices = allometry_choices, multiple = TRUE
  ),
  shinyjs::hidden(
    shiny::uiOutput('allo_values')
  ),
  # spatial
  shiny::selectInput(
    'spatial', 'Spatial ambit', choices = spatial_choices, multiple = TRUE
  ),
  shinyjs::hidden(
    shiny::uiOutput('spatial_values')
  ),
  # functional group
  shiny::selectInput(
    'functgroup', 'Functional group', choices = functgroup_choices,
    multiple = TRUE
  ),
  shinyjs::hidden(
    shiny::div(
      id = 'functgroup_values_div',
      shiny::uiOutput('functgroup_values')
    )
  ),
  # vars
  shiny::selectInput(
    'depvar', 'Dependent variable',
    choices = depvar_choices, multiple = TRUE
  ),
  shiny::selectInput(
    'indepvars', 'Independent variables',
    choices = indepvars_choices, multiple = TRUE
  ),
  # other
  shiny::selectInput(
    'cubication', 'Cubication shape', choices = cubication_choices,
    multiple = TRUE
  ),
  shiny::selectInput(
    'specialparam', 'Special parameter',
    choices = specialparam_choices, multiple = TRUE
  )
)

# observer to show the ui for the allometry level values
shiny::observe({
  allometry_level <- input$allolvl
  if (is.null(allometry_level) || allometry_level == '') {
    shinyjs::hide('allo_values')
  } else {
    shinyjs::show('allo_values')
  }
})
# observer to show the ui for spatial values
shiny::observe({
  spatial <- input$spatial
  if (is.null(spatial) || spatial == '') {
    shinyjs::hide('spatial_values')
  } else {
    shinyjs::show('spatial_values')
  }
})
output$spatial_values <- shiny::renderUI({
  # spatial level
  spatial_vals <- input$spatial
  # debug
  browser()
  # choices
  spatial_values_choices <- allometries_table %>%
    dplyr::filter(spatial_level %in% spatial_vals) %>%
    dplyr::pull(spatial_name) %>% unique() %>% sort()
  # UI
  shiny::tagList(
    shiny::selectInput(
      'spatial_values_input', 'Select the spatial ambit values',
      choices = spatial_values_choices, multiple = TRUE
    )
  )
})
# observer to show the ui for functional group values
shiny::observeEvent(
  eventExpr = input$functgroup,
  handlerExpr = {
    if (is.null(input$functgroup) || input$functgroup == '') {
      shinyjs::hide('functgroup_values_div')
    } else {
      shinyjs::show('functgroup_values_div')
    }
  }
)
output$functgroup_values <- shiny::renderUI({
  # functgroup level
  functgroup_vals <- input$functgroup
  # choices
  functgroup_values_choices <- allometries_table %>%
    dplyr::filter(functional_group_level %in% functgroup_vals) %>%
    dplyr::pull(functional_group_name) %>% unique() %>% sort()
  # UI
  shiny::tagList(
    shiny::selectInput(
      'functgroup_values_input', 'Select the functional group values',
      choices = functgroup_values_choices, multiple = TRUE
    )
  )
})

# reactive to create the filtering expression
filtering_expr <- shiny::reactive({
  # filter exprs
  rlang::quos(
    allometry_level %in% !! input$allolvl,
    spatial_level %in% !! input$spatial,
    spatial_name %in% !! input$spatial_values_input,
    functional_group_level %in% !! input$functgroup,
    functional_group_name %in% !! input$functgroup_values_input,
    dependent_var %in% !! input$depvar,
    independent_var_1 %in% !! input$indepvars |
      independent_var_2 %in% !! input$indepvars |
      independent_var_3 %in% !! input$indepvars,
    cubication_shape %in% !! input$cubication,
    special_parameter %in% !! input$specialparam
  ) %>%
    # removing null or empty inputs
    magrittr::extract(!purrr::map_lgl(list(
      input$allolvl,
      input$spatial,
      input$spatial_values_input,
      input$functgroup,
      input$functgroup_values_input,
      input$depvar,
      input$indepvars,
      input$cubication,
      input$specialparam
    ), is.null))
})
```

Glance
=====================================

Column {data-width=150}
-------------------------------------

### Equations available

```{r eq_vb}
compute_equations <- reactive({
  allometries_table %>%
    dplyr::filter(!!! filtering_expr()) %>%
    pull(equation) %>%
    unique() %>% length()
})

renderValueBox({
  valueBox(compute_equations(), icon = 'fa-calculator')
})
```

### 
    
```{r eq_selected}
renderTable({
  allometries_table %>%
    dplyr::filter(!!! filtering_expr()) %>%
    select(equation) %>%
    distinct()
}, align = 'c')
```

Column {data-width=200}
-------------------------------------

### Independent variables available
    
```{r indep_var}
compute_indep_vars <- reactive({
  allometries_table %>%
    dplyr::filter(!!! filtering_expr()) %>%
    select(starts_with('independent_')) %>%
    flatten_chr() %>%
    unique() %>%
    magrittr::extract(!is.na(.)) %>%
    length()
})

renderValueBox({
  valueBox(compute_indep_vars(), icon = 'fa-chart-line')
})

```

###

```{r indep_var_plot}
# renderHighchart({
#   allometries_table %>%
#     dplyr::filter(!!! filtering_expr()) %>%
#     gather('indep_var_order', 'indep_vars', starts_with('independent_')) %>%
#     pull(indep_vars) %>%
#     hchart(type = 'column', name = 'Allometries') %>%
#     hc_yAxis(
#       title = list(text = 'Number of equations')
#     ) %>%
#     hc_legend() %>%
#     hc_add_theme(hc_theme_flatdark())
# })
# renderPlot({
#   allometries_table %>%
#     dplyr::filter(!!! filtering_expr()) %>%
#     gather('indep_var_order', 'indep_vars', starts_with('independent_')) %>%
#     filter(!is.na(indep_vars)) %>%
#     ggplot() +
#     geom_bar(aes(x = indep_vars, fill = indep_vars), show.legend = FALSE)
# })
renderPlotly({
  p <- allometries_table %>%
    dplyr::filter(!!! filtering_expr()) %>%
    gather('indep_var_order', 'indep_vars', starts_with('independent_')) %>%
    filter(!is.na(indep_vars)) %>%
    ggplot() +
    geom_bar(aes(x = indep_vars, fill = indep_vars), show.legend = FALSE) +
    scale_fill_viridis_d() +
    guides(fill = FALSE)
  
  ggplotly(p, tooltip = 'y') %>% hide_legend()
})
```

### Spatial ambits
    
```{r spatial_ambits}
compute_spatial_ambits <- reactive({
  allometries_table %>%
    dplyr::filter(!!! filtering_expr()) %>%
    select(starts_with('spatial_'))
})

renderValueBox({
  valueBox(
    compute_spatial_ambits() %>% pull(spatial_level) %>% unique() %>% length(),
    icon = 'fa-chart-line'
  )
})
```

### Spatial names
    
```{r spatial_names}
compute_spatial_names <- reactive({
  allometries_table %>%
    dplyr::filter(!!! filtering_expr()) %>%
    select(starts_with('spatial_'))
})

renderValueBox({
  valueBox(
    compute_spatial_names() %>% pull(spatial_name) %>% unique() %>% length(),
    icon = 'fa-chart-line'
  )
})
```

### 

```{r spatial_plot}
# renderHighchart({
#   allometries_table %>%
#     dplyr::filter(!!! filtering_expr()) %>%
#     count(spatial_level) %>%
#     hchart(type = 'column', name = 'Allometries', hcaes(x = spatial_level, y = n, group = spatial_level)) %>%
#     hc_yAxis(
#       title = list(text = 'Number of equations')
#     ) %>%
#     hc_legend() %>%
#     hc_add_theme(hc_theme_flatdark())
# })
# renderPlot({
#   allometries_table %>%
#     dplyr::filter(!!! filtering_expr()) %>%
#     count(spatial_level, spatial_name) %>%
#     ggplot() +
#     geom_col(aes(x = spatial_level, y = n, fill = spatial_name), show.legend = FALSE)
# })
renderPlotly({
  p <- allometries_table %>%
    dplyr::filter(!!! filtering_expr()) %>%
    count(spatial_level, spatial_name) %>%
    ggplot() +
    geom_col(aes(x = spatial_level, y = n, fill = spatial_name), show.legend = FALSE) +
    scale_fill_viridis_d() +
    guides(fill = FALSE)
  
  ggplotly(p, tooltip = c('y', 'fill')) %>% hide_legend()
})
```


Column {data-width=200}
-------------------------------------

### Species

```{r species_vb}
compute_functional_groups <- reactive({
  allometries_table %>%
    dplyr::filter(!!! filtering_expr()) %>%
    select(starts_with('functional_'))
})

renderValueBox({
  valueBox(
    compute_functional_groups() %>%
      distinct() %>% 
      filter(functional_group_level == 'species') %>%
      pull(functional_group_level) %>%
      length(),
    icon = 'fa-chart-line'
  )
})

```

### Genus

```{r genus_vb}
renderValueBox({
  valueBox(
    compute_functional_groups() %>%
      distinct() %>% 
      filter(functional_group_level == 'genus') %>%
      pull(functional_group_level) %>%
      length(),
    icon = 'fa-chart-line'
  )
})
```

###

```{r fgs_plot}
# renderHighchart({
#   compute_functional_groups() %>%
#     count(spatial_level) %>%
#     hchart(type = 'column', name = 'Allometries', hcaes(x = spatial_level, y = n, group = spatial_level)) %>%
#     hc_yAxis(
#       title = list(text = 'Number of equations')
#     ) %>%
#     hc_legend() %>%
#     hc_add_theme(hc_theme_flatdark())
# })
# renderPlot({
#   compute_functional_groups() %>%
#     count(functional_group_level, functional_group_name) %>%
#     ggplot() +
#     geom_col(aes(x = functional_group_level, y = n, fill = functional_group_name), show.legend = FALSE)
# })
renderPlotly({
  p <- compute_functional_groups() %>%
    count(functional_group_level, functional_group_name) %>%
    ggplot() +
    geom_col(aes(x = functional_group_level, y = n, fill = functional_group_name)) +
    scale_fill_viridis_d() +
    guides(fill = FALSE)
  
  ggplotly(p, tooltip = c('y', 'fill')) %>% hide_legend()
})
```

### Plant level allometries

```{r plant_level_vb}
compute_plant_level <- reactive({
  allometries_table %>%
    dplyr::filter(!!! filtering_expr()) %>%
    select(starts_with('allometry_'))
})

renderValueBox({
  valueBox(
    compute_plant_level() %>% 
      filter(allometry_level == 'tree') %>%
      pull(allometry_name) %>%
      length(),
    icon = 'fa-chart-line'
  )
})

```

### Organ level allometries

```{r plant_level_organ_vb}
renderValueBox({
  valueBox(
    compute_plant_level() %>% 
      filter(allometry_level == 'organ') %>%
      pull(allometry_name) %>%
      length(),
    icon = 'fa-chart-line'
  )
})
```


Table {data-orientation=rows}
=====================================

Row {data-height=50}
-------------------------------------

###

```{r save_table}
downloadLink('save_csv', 'csv')
output$save_csv <- downloadHandler(
  filename = function() {
    paste("allometries_", Sys.Date(), '.csv', sep = '')
  },
  content = function(file) {
    
    data_res <- allometries_table %>%
    dplyr::filter(!!! filtering_expr())
    
    write_csv(data_res, file)
  }
)
```

###

```{r save_table_2}
downloadLink('save_xlsx', 'xlsx')
output$save_xlsx <- downloadHandler(
  filename = function() {
    paste("allometries_", Sys.Date(), '.xlsx', sep = '')
  },
  content = function(file) {
    
    data_res <- allometries_table %>%
    dplyr::filter(!!! filtering_expr())
    
    write_xlsx(data_res, file)
  }
)
```


Row
-------------------------------------

### Table
    
```{r table_output}
# table output
# DT::renderDT({
#   allometries_table %>%
#     # filtering step, based on the data inputs
#     dplyr::filter(!!! filtering_expr()) %>%
#     # DT
#     DT::datatable(
#       class = 'compact hover nowrap row-border order-column',
#       options = list(
#         dom = 't',
#         paging = FALSE,
#         scrollCollapse = TRUE, deferRender = TRUE, scrollX = TRUE,
#         fillContainer = TRUE
#       )
#     )
# })
# renderTable({
#   allometries_table %>%
#     dplyr::filter(!!! filtering_expr())
# }, digits = 2)
DT::renderDT({
  dt_data <- allometries_table %>%
    dplyr::filter(!!! filtering_expr())
  
  dt_data %>%
    DT::datatable(
      class = 'compact hover nowrap row-border order-column',
      options = list(
        dom = 'tp',
        pageLength = 50,
        columnDefs = list(list(className = 'dt-right', targets = '_all'))
      )
    ) %>%
    DT::formatRound(dt_data %>% map_lgl(is.numeric), digits = 2)
})
```

Calculate
=====================================

### Por desarrollar

```{r}

```

